-- QUERY 1: HOW TO CREATE NEW DATABASE?
CREATE  DATABASE  [DB_OBJECTS]

-- QUERY 2: HOW TO CONNECT TO ABOVE DATABASE?
USE [DB_OBJECTS]

-- QUERY 3: HOW TO CREATE TABLE FOR DATA STORAGE?
CREATE TABLE tblProducts
(
ProductID		INTEGER,	 	-- this column stores DIGITS : 0, -10, 99, etc..	
ProductName		CHARACTER(40),	-- this column stores up to 40 CHARACTERS [DIGITS, SYMBOLS, ALPHABETS]
Price			INT,			-- this column stores DIGITS : 0, -10, 99, etc..	
Size			Char(10)		-- this column stores up to 10 CHARACTERS [DIGITS, SYMBOLS, ALPHABETS]
)

-- QUERY 4: HOW TO STORE DATA INTO ABOVE TABLE?
INSERT INTO  tblProducts VALUES (1001, 'CAPS', 10, 'S')


-- QUERY 5: HOW TO INSERT MULTIPLE ROWS IN ABOVE TABLE?
INSERT		 tblProducts VALUES (1002, 'BALLS', 11, 'S'),  (1003, 'BALLS', 12, 'M');


-- QUERY 6: HOW TO REPORT ABOVE INSERTED TABLE DATA?
SELECT * FROM  tblProducts					-- * MEANS TO REPORT ALL COLUMNS FROM THE TABLE

/* TABLE SCAN		:	A PROPERTY OF SQL SERVER USING WHICH THE DATA BEING INSERTED IS STORED IN THE 
						SAME ORDER AND REPORTED IN THE SAME ORDER. 

						INSERTION ORDER = STORAGE ORDER = REPORTING ORDER		*/


