-- USING GUI, CREATE DATABASE WITH 3 FILEGROUPS : PRIMARY, ACCOUNTS, INSURANCE
-- ADD ONE OR MORE FILES TO EACH OF THE ABOVE FILEGROUP

-- OR USE BELOW SCRIPT:
CREATE DATABASE [BANKING_DATABASE]
ON  PRIMARY 
( NAME = N'BANK_DATABASE', FILENAME = N'D:\BANK_DATABASE.mdf' ), 
 FILEGROUP [ACCOUNTS_FILEGROUP] 
( NAME = N'ACCOUNTS_FILE1', FILENAME = N'D:\ACCOUNTS_FILE1.ndf'), 
( NAME = N'ACCOUNTS_FILE2', FILENAME = N'D:\ACCOUNTS_FILE2.ndf'),
 FILEGROUP [INSURANCE_FILEGROUP] 
( NAME = N'INSURANCE_FILE', FILENAME = N'D:\INSURANCE_FILE.ndf')


USE [BANKING_DATABASE]


CREATE TABLE tblACCOUNTS (AccID int, AccStatus bit, AccBal float) on [ACCOUNTS_FILEGROUP]
INSERT INTO tblAccounts VALUES (10001, 797009, 1), (10002, 343733, 1),(10003, 0, 1)


CREATE TABLE tblINSURANCE (InsrID int, InsrStatus bit, InsrBal float) on [INSURANCE_FILEGROUP]
INSERT INTO tblInsurance VALUES (10001, 457444, 1), (10002, 347333, 1),(10003, 440, 1)


-- FULL BACKUP			:	THIS IS THE COMPLETE DATABASE BACKUP (BASE BACKUP)					-- 12 AM
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'D:\FullBackup.BAK' with FORMAT	-- FORMAT : TO OVERWRITE

-- DIFFERENTIAL BACKUP	:	 ALL CHANGES SINCE LATEST FULL BACKUP								-- 12 AM TO 1 AM
INSERT INTO tblINSURANCE DEFAULT VALUES; 
INSERT INTO tblACCOUNTS DEFAULT VALUES
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'D:\Diff_1.BAK' with FORMAT, DIFFERENTIAL

-- DIFFERENTIAL BACKUP	:	 ALL CHANGES SINCE LATEST FULL BACKUP								-- 12 AM TO 2 AM
INSERT INTO tblINSURANCE DEFAULT VALUES; INSERT INTO tblACCOUNTS DEFAULT VALUES
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'D:\Diff_2.BAK' with FORMAT, DIFFERENTIAL

-- LOG BACKUP																					-- LOG DATA @ 3 AM
INSERT INTO tblINSURANCE DEFAULT VALUES; INSERT INTO tblACCOUNTS DEFAULT VALUES
BACKUP LOG [BANKING_DATABASE] TO DISK = 'D:\LogBackup.trn' with FORMAT

-- COPY ONLY BACKUP	:	SUCH FULL BACKUP THAT DO NOT BE A BASE FOR REMAINING DIFFERENTIAL & LOG BACKUPS	-- 4 AM
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'D:\Backup.BAK' with FORMAT, COPY_ONLY

BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'D:\Diff_3.BAK' with FORMAT, DIFFERENTIAL			-- SINCE 12 AM OR 4 AM ???   12 AM

-- PARTIAL BACKUP	:	SUCH BACKUPS THAT ARE PERFORMED ON READ WRITE FILEGROUPS OF THE DATABASE. READ ONLY FILEGROUPS ARE SKIPPED.
BACKUP DATABASE [BANKING_DATABASE] read_write_filegroups TO DISK = 'D:\pBackups.BAK' 

-- MIRRORED BACKUP	:	1ST BACKUP FILE IS A DUPLICATE COPY OF 2ND BACKUP FILE. 
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'D:\PRODUCTDB_BACKUP_COPY1.bak' MIRROR TO DISK = 'D:\PRODUCTDB_BACKUP_COPY2.bak' WITH FORMAT

-- SPLIT BACKUP		:	1ST BACKUP FILE IS A CONTINOUS PART TO 2ND BACKUP FILE. BACKUP INFO IS SPLIT INTO EQUAL PARTITIONS.	BACKUPSET
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'D:\PRODUCTDB_BACKUP_PART1.bak', DISK = 'D:\PRODUCTDB_BACKUP_PART2.bak' WITH FORMAT


USE MSDB 
GO

select * from backupset				-- CONTAINS AN ENTRY FOR EVERY BACKUP OPERATION WE PERFORM IN THE SERVER
									-- TYPE COLUMN VALUE :	D [FULL], I [DIFFERENTIAL], L [LOG]

select * from backupmediafamily		-- CONTAINS AN ENTRY FOR EVERY LOCATION USED IN BACKUP STATEMENTS

-- TASK 1:	HOW TO AUDIT LIST OF ALL FULL BACKUPS FOR A GIVEN DATABASE?
-- TASK 2:	HOW TO AUDIT LATEST FULL BACKUP FOR A GIVEN DATABASE?
-- TASK 3:	HOW TO AUDIT LATEST DIFFERENTIAL BACKUP FOR A GIVEN DATABASE?


							   s
-- HOW TO SCHEDULE BACKUPS?
-- USING JOBS

-- RIGHT CLICK SQL SERVER AGENT > START
-- RIGHT CLICK SQL SERVER AGENT > NEW JOB > NAME, STEP > PASTE BACKUP SCRIPT, SCHEDULE (EVERY DAY) > OK

-- RIGHT CLICK THE ABOVE JOB > START JOB AT STEP

-- RIGHT CLICK DATABASE  > TASKS > TAKE OFFLINE
-- RIGHT CLICK THE ABOVE JOB > START JOB AT STEP. WE SEE ERROR.
-- TO GET THE ACTUAL ERROR DETAILS  : RIGHT CLICK THE ABOVE JOB > VIEW HISTORY
-- RIGHT CLICK DATABASE  > TASKS > TAKE OFFLINE
-- RIGHT CLICK THE ABOVE JOB > START JOB AT STEP. NO ERROR. 

ALTER DATABASE [PRODUCT DATABASE] SET RECOVERY FULL 		-- FOR OLTP DATABASES
ALTER DATABASE [PRODUCT DATABASE] SET RECOVERY SIMPLE 		-- FOR STANDBY DATABASES
ALTER DATABASE [PRODUCT DATABASE] SET RECOVERY BULK_LOGGED  -- FOR DWH DATABASES


