CREATE DATABASE [BANKING_DATABASE]
ON  PRIMARY 
( NAME = N'BANK_DATABASE', FILENAME = N'E:\BANKDATABASE.mdf' ), 
 FILEGROUP [ACCOUNTS_FILEGROUP] 
( NAME = N'ACCOUNTS_FILE', FILENAME = N'E:\ACCOUNTSFILE.ndf'), 
 FILEGROUP [INSURANCE_FILEGROUP] 
( NAME = N'INSURANCE_FILE', FILENAME = N'E:\INSURANCEFILE.ndf')


USE [BANKING_DATABASE]

CREATE TABLE tblACCOUNTS (AccID int, AccStatus bit, AccBal float) on [ACCOUNTS_FILEGROUP]
INSERT INTO tblAccounts VALUES (10001, 797009, 1), (10002, 343733, 1),(10003, 0, 1)

CREATE TABLE tblINSURANCE (InsrID int, InsrStatus bit, InsrBal float) on [INSURANCE_FILEGROUP]
INSERT INTO tblInsurance VALUES (10001, 457444, 1), (10002, 347333, 1),(10003, 440, 1)


-- FULL BACKUP			:	THIS IS THE COMPLETE DATABASE BACKUP (BASE BACKUP)					-- 12 AM
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'E:\FullBackup.BAK' with FORMAT			-- FORMAT : TO OVERWRITE

-- DIFFERENTIAL BACKUP	:	 ALL CHANGES SINCE LATEST FULL BACKUP								-- 12 AM TO 1 AM
INSERT INTO tblINSURANCE DEFAULT VALUES; INSERT INTO tblACCOUNTS DEFAULT VALUES
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'E:\Diff_1.BAK' with FORMAT, DIFFERENTIAL

-- DIFFERENTIAL BACKUP	:	 ALL CHANGES SINCE LATEST FULL BACKUP								-- 12 AM TO 2 AM
INSERT INTO tblINSURANCE DEFAULT VALUES; INSERT INTO tblACCOUNTS DEFAULT VALUES
BACKUP DATABASE [BANKING_DATABASE] TO DISK = 'E:\Diff_2.BAK' with FORMAT, DIFFERENTIAL

-- LOG BACKUP																					-- LOG DATA @ 3 AM
INSERT INTO tblINSURANCE DEFAULT VALUES; INSERT INTO tblACCOUNTS DEFAULT VALUES
BACKUP LOG [BANKING_DATABASE] TO DISK = 'E:\LogBackup.trn' with FORMAT


USE MASTER 

drop database [BANKING_DATABASE]


-- EXAMPLE 1: HOW TO RESTORE OR RECOVER THE ENTIRE DATABASE?
RESTORE DATABASE BANKDATABASE FROM DISK = 'D:\FullBackup.BAK'	WITH NORECOVERY
RESTORE DATABASE BANKDATABASE FROM DISK = 'D:\Diff_2.BAK'		WITH NORECOVERY
RESTORE DATABASE BANKDATABASE FROM DISK = 'D:\LogBackup.trn'	WITH RECOVERY


USE MASTER 
drop database BANKDATABASE


-- EXAMPLE 2: HOW TO RESTORE THE DATABASE IN PARTS?  PARTIAL RESTORE.
-- REQUIREMENT: NEED TO RESTORE ACCOUNTS DATA FIRST. GET DATABASE ONLINE. 
-- LATER, YOU NEED TO RESTORE INSURANCE DATA.
RESTORE DATABASE BANKDATABASE 
FILEGROUP = 'PRIMARY' FROM DISK = 'D:\FullBackup.BAK'	WITH NORECOVERY, PARTIAL

RESTORE DATABASE BANKDATABASE 
FILEGROUP = 'ACCOUNTS_FILEGROUP' FROM DISK = 'D:\FullBackup.BAK' WITH NORECOVERY

RESTORE DATABASE BANKDATABASE FROM DISK = 'D:\Diff_2.BAK'		WITH NORECOVERY
RESTORE LOG BANKDATABASE FROM DISK = 'D:\LogBackup.trn'	WITH RECOVERY


USE BANKDATABASE
SELECT COUNT(*) FROM tblACCOUNTS			-- NO ERROR
SELECT COUNT(*) FROM tblINSURANCE			-- ERROR #8653.  TABLE IS OFFLINE	



-- HOW TO RESTORE REMAINING PART OF DATABASE?
-- PERFORM TAIL LOG BACKUP : TO CONVERT ONLINE DATABASE INTO RESTORING STATE.
USE MASTER  
GO
BACKUP LOG BANKDATABASE TO DISK = 'E:\TAIL_LOG.TRN' WITH NORECOVERY, FORMAT		-- TAIL LOG BACKUP


RESTORE DATABASE BANKDATABASE 
FILEGROUP = 'INSURANCE_FILEGROUP' FROM DISK = 'E:\FullBackup.BAK'	WITH NORECOVERY


RESTORE DATABASE BANKDATABASE FROM DISK = 'E:\Diff_2.BAK'		WITH NORECOVERY
RESTORE LOG BANKDATABASE FROM DISK = 'E:\LogBackup.trn'	WITH NORECOVERY
RESTORE LOG BANKDATABASE FROM DISK = 'E:\TAIL_LOG.TRN' WITH RECOVERY


USE BANKDATABASE
SELECT COUNT(*) FROM tblACCOUNTS
SELECT COUNT(*) FROM tblINSURANCE		-- NO ERROR	

/*
RECOVERY MODELS:
	FULL		:	EVERY OPERATION IS COMPLETELY LOGGED IN LOG FILE. EASY RECOVERY.
					USED FOR PRODUCTION DATABASE

	SIMPLE		:	MINIMAL LOGGING OF TRANSACTION DETAILS. NO DATA IS LOGGED. LESS LOG SPACE
					USED FOR READONLY / STANDBY DATABASES. log backup is not possible. 

	BULK LOGGED	:	ALL OPERATIONS ARE COMPLETELY LOGGED EXCEPT BULK OPERATIONS (IMPORT/EXPORT)
					USED FOR ETL 

	ALTER DATABASE [BANKDATABASE] SET RECOVERY SIMPLE WITH NO_WAIT
*/


/*
TASK 1	:	CAN YOU RESTORE THE SAME LOG BACKUP MORE THAN ONCE?

TASK 2	:	YOU ARE AN ADMIN FOR A DATABASE.
			VERY RECENTLY,THERE WERE FEW MANAGEMENT OPERATIONS ON THE DATABASE BY PM TEAM
			HOW DO YOU VERIFY IF DATABASE IS PARTIALLY ONLINE OR COMPLETELY ONLINE?

			NOTE:  THERE ARE NO COMMANDS FOR THIS.

TASK 3	:	IN SIMPLE RECOVERY MODEL, LOG BACKUP IS NOT POSSIBLE. AS A RESULT,  WHAT ELSE IS NOT POSSIBLE ???
*/

