

CREATE TABLE RESERVATION
(
CRAFT_CODE VARCHAR(30) PRIMARY KEY,
NO_OF_SEATS INT CHECK (NO_OF_SEATS > 10),
CLASS VARCHAR(30) CHECK (CLASS IN ('EC', 'BIZ')) 
)

INSERT INTO RESERVATION VALUES 	('AI01', 11, 'EC'), 	('AI02', 12, 'EC'), 
									('AI03', 13, 'EC'), 	('AI04', 14, 'EC')
SELECT * FROM RESERVATION


-- TASK 1:  WRITE A PROCEDURE TO REPORT DATA IN BELOW FORMAT BASED ON INPUT VALUES?
-- THERE ARE 4 RESERVATIONS WITH NUMBER OF SEATS ABOVE 1

CREATE PROC uspReportRowCount1 (@seats int, @rcount int OUT)		-- OUT IS THE DIRECTION OF PARAMETER
AS
BEGIN
SELECT @rcount = COUNT(*) FROM RESERVATION WHERE NO_OF_SEATS > @seats
END


DECLARE @VAR_IN INT, @VAR_OUT INT	
SET @VAR_IN = 1				
EXECUTE uspReportRowCount1 1, @VAR_OUT OUT
SELECT 'THERE ARE ' + CONVERT(VARCHAR(10), @VAR_OUT) + ' RESERVATIONS WITH NUMBER OF SEATS ABOVE ' + CONVERT(VARCHAR(10), @VAR_IN)



-- TASK 2:  WRITE A PROCEDURE TO ACCEPT A TABLE AND REPORT LIST OF CONSTRAINTS?
CREATE PROCEDURE USPREPORT_CONSTRAINTS (@TABLENAME VARCHAR(30))
AS
SELECT * FROM SYS.OBJECTS  WHERE TYPE IN ('C', 'F', 'PK', 'UQ', 'D') AND parent_object_id = OBJECT_ID(@TABLENAME)

EXEC USPREPORT_CONSTRAINTS 'RESERVATION'


-- TASK 3:  WRITE A PROCEDURE TO IDENTIFY THE LIST OF DUPLICATE ROWS IN A TABLE?
PLEASE REFER TO THE SQL SERVER DOC GIVEN EARLIER FOR THIS SOLUTION

-- TASK 4:  WRITE A PROCEDURE TO REMOVE THE DUPLICATED ROWS IN A TABLE?
PLEASE REFER TO THE SQL SERVER DOC GIVEN EARLIER FOR THIS SOLUTION