USE EMPLOYEEDATABASE

-- HOW TO FIND ORPHAN USERS ? 	ORPHAN USERS	: SUCH USERS WHOSE LOGIN IS MISSING.
SELECT dp.type_desc, dp.SID, dp.name AS user_name  
FROM sys.database_principals AS dp  
LEFT OUTER JOIN sys.server_principals AS sp  
ON dp.SID = sp.SID  
WHERE sp.SID IS NULL  AND authentication_type_desc = 'INSTANCE';


-- HOW TO RESOLVE ORPHAN USERS ? 
/*	Step 1: From Source server > Export all logins to an RPT file	
			SELECT * FROM SYSLOGINS
 			RIGHT CLICK QUERY  > RESULTS TO > FILE. THEN SELECT QUERY > EXECUTE > SAVE THE FILE.
	
	Step 2: On Destination : 
			EXEC  SP_RESOLVE_LOGINS 'EMPLOYEEDATABASE', 'E:\', 'LOGINS_REPORT.rpt'  */


-- HOW TO PREVENT ORPHAN USERS?  [CONTAINED DATABASES OR CONTAINMENT USERS]
-- A TECHNIQUE USED TO CREATE USERS WITHOUT ANY LOGINS. 
USE MASTER 
GO
EXEC sp_configure 'show advanced', 1
EXEC sp_configure 'contained database authentication', 1
RECONFIGURE


ALTER DATABASE [PRODUCTDATABASE]  SET CONTAINMENT = PARTIAL   
USE  [PRODUCTDATABASE]

CREATE USER [USER_SAM] WITH PASSWORD=N'PASS@123$', DEFAULT_SCHEMA=[dbo]   
ALTER ROLE DB_DATAREADER ADD MEMBER [USER_SAM]
-- TEST CONTAINMENT USER: SSMS > USERNAME, PASSWORD , OPTIONS : DB NAME >> CONNECT


  