use [DB_OBJECTS]
go

-- REQUIREMENT : HOW TO REPORT ONE ROW AT A TIME FROM ABOVE TABLE?
-- SOLUTION : CURSORS
-- CURSORS ARE VARIABLES USED TO ACCESS THE TABLE DATA ON A ROW BY ROW BASIS.
-- MEANS, WE CAN ACCESS ONLY ONE ROW AT A TIME.

-- EXAMPLE 1:
DECLARE CRS CURSOR
FOR
SELECT * FROM PRODUCTS_DATA
OPEN CRS 
FETCH NEXT FROM CRS 
FETCH NEXT FROM CRS 
FETCH NEXT FROM CRS 
FETCH NEXT FROM CRS 
CLOSE CRS 
DEALLOCATE CRS 


-- EXAMPLE 2:
DECLARE CRS CURSOR
STATIC				-- OPPOSITE : DYNAMIC 			
SCROLL				-- OPPOSITE : FORWARD_ONLY			
GLOBAL				-- OPPOSITE : LOCAL		
FOR
SELECT * FROM PRODUCTS_DATA
OPEN CRS 
FETCH FIRST FROM CRS 
FETCH ABSOLUTE 5 FROM CRS 
FETCH NEXT FROM CRS
FETCH NEXT FROM CRS
FETCH LAST FROM CRS 
FETCH PRIOR FROM CRS 
FETCH FIRST FROM CRS 
CLOSE CRS 
DEALLOCATE CRS 

USE [DB_OBJECTS] 
GO

-- REQUIREMENT :	REPORT LIST OF ALL TABLES AND NUMBER OF ROWS IN EACH TABLE IN THE DATABASE
SELECT * FROM SYS.TABLES 
SELECT COUNT(*) AS RCOUNT FROM TIME_DATA
SELECT TIME_DATA AS TABLENAME, COUNT(*) AS RCOUNT FROM TIME_DATA			-- ERROR
SELECT 'TIME_DATA' AS TABLENAME, COUNT(*) AS RCOUNT FROM TIME_DATA

-- FORMAT:
SELECT '??????' AS TABLENAME, COUNT(*) AS RCOUNT FROM ???????

-- SOLUTION V1:
DECLARE CRS CURSOR 
FOR
SELECT NAME FROM SYS.TABLES 
DECLARE @TNAME VARCHAR(30), @QUERY NVARCHAR(MAX)   --NVARCHAR : UNICODE DATA.  2GB SOACE
OPEN CRS 
FETCH NEXT FROM CRS INTO @TNAME			-- THIS IS TO FETCH 1ST TABLE NAME
WHILE @@FETCH_STATUS =  0				-- AS LONG AS CURSOR HAS MORE ROWS TO FETCH
	BEGIN
	SET @QUERY = 'SELECT '''+@TNAME+''' AS TABLENAME, COUNT(*) AS RCOUNT FROM ' + @TNAME
	EXEC SP_EXECUTESQL @QUERY
	FETCH NEXT FROM CRS INTO @TNAME	
	END 
DEALLOCATE CRS

-- SOLUTION V2:
CREATE PROC USP_REPORTDATA
AS
DECLARE CRS CURSOR 
FOR
SELECT NAME FROM SYS.TABLES 
DECLARE @TNAME VARCHAR(30), @QUERY NVARCHAR(MAX)   --NVARCHAR : UNICODE DATA.  2GB SOACE
OPEN CRS 
FETCH NEXT FROM CRS INTO @TNAME			-- THIS IS TO FETCH 1ST TABLE NAME
WHILE @@FETCH_STATUS =  0				-- AS LONG AS CURSOR HAS MORE ROWS TO FETCH
	BEGIN
	SET @QUERY = 'SELECT '''+@TNAME+''' AS TABLENAME, COUNT(*) AS RCOUNT FROM ' + @TNAME
	EXEC SP_EXECUTESQL @QUERY
	FETCH NEXT FROM CRS INTO @TNAME	
	END 
DEALLOCATE CRS

DROP TABLE tblReportRcount
CREATE TABLE tblReportRcount (Tname varchar(30), rcount bigint)
INSERT INTO tblReportRcount EXEC USP_REPORTDATA
SELECT * FROM tblReportRcount