SELECT SERVERPROPERTY('PRODUCTLEVEL')



/*

TASK 1:		CONFIGURE REPLICATION. 
			ADD FEW COLUMNS TO EXISTING ARTICLE. WILL THIS BE REPLICATED?

			ADD FEW TABLES TO THE DATABASE. WILL THESE BE REPLICATED?

			TRUNCATE DATA IN REPLICATED OBJECTS. WILL THESE BE REPLICATED?


TASK 2:		HOW TO REMOVE ARTCILE FROM EXISTING REPLICATION?


TASK 3:		WHAT ARE THE DIFFERENCES BETWEEEN A UNIQUE KEY AND PRIMARY KEY?
			PRIMARY KEY DEFINES A CLUSTERED INDEX. MANDATORY FOR LOG READER AGENT IN REPL
			UNIQUE KEY DEFINES A NONCLUSTERED INDEX. OPTIONAL FOR REPL. AGENTS

*/
