-- STEP 1:	CONNECT TO MASTER DATABASE
-- STEP 2:	CREATE LOGIN IN THE MASTER DATABASE, SET A PASSWORD. 
CREATE LOGIN JOHN_LOGIN WITH PASSWORD = 'azureserver@123'

-- STEP 3:	CREATE USER FOR ABOVE LOGIN IN THE MASTER DATABASE
CREATE USER USER_JOHN FOR LOGIN JOHN_LOGIN


-- STEP 4:	CONNECT TO REQUIRED PRODUCTION DATABASE
-- STEP 5:	CREATE USER FOR ABOVE LOGIN IN THE PRODUCTION DATABASE
CREATE USER USER_JOHN FOR LOGIN JOHN_LOGIN


-- STEP 6:	COLUMN LEVEL PERMISSIONS
GRANT SELECT ON SALES_DATA(SALESAMOUNT) TO USER_JOHN

-- STEP 7:	OBJECT LEVEL PERMISSIONS
GRANT SELECT ON SALES_DATA TO USER_JOHN WITH GRANT OPTION


-- STEP 8:	SCHEMA LEVEL PERMISSIONS
GRANT SELECT ON SCHEMA::DBO TO USER_JOHN WITH GRANT OPTION


-- STEP 9:	ROLE LEVEL PERMISSIONS
CREATE ROLE ROLE1
ALTER ROLE ROLE1 ADD MEMBER USER_JOHN
GRANT SELECT ON CUSTOMERS_DATA TO ROLE1


-- STEP 10: DATABASE LEVEL PERMISSIONS
ALTER ROLE DB_DATAREADER ADD MEMBER ROLE1