
USE [PRODUCT DATABASE]

SELECT * FROM [CUSTOMERS_DATA]

SELECT * FROM [CUSTOMERS_DATA] 
WHERE ENGLISHOCCUPATION LIKE '%Professional%'


SELECT * FROM [CUSTOMERS_DATA] 
WHERE  CONTAINS (ENGLISHOCCUPATION,'Professional')		-- EXACT MATCH DATA

SELECT * FROM [CUSTOMERS_DATA]
WHERE  CONTAINS (ENGLISHEDUCATION,'Professional')		-- ERROR. REASON: ENGLISHEDUCATION COLUMN HAS NO FT INDEX

SELECT * FROM [CUSTOMERS_DATA]
WHERE  FREETEXT (ENGLISHOCCUPATION,'Professional')    -- EXACT MATCH DATA  & CLOSEST MATCH DATA 


/* FUZZY MATCH  MEANS CLOSEST MATCH. EX:  PROFESSIONAL   = TALENTED = TECHNICAL = SKILLED 
THESE SYNONYMS ARE STORED  / MAINTAINED IN THE "THESAURUS" FILE. 
*/
