--CREATE DATABASE GROUPBY_TEMPDB
 
USE [DB_OBJECTS] 

CREATE TABLE tblPopulation
(
Country VARCHAR(100),
[State] VARCHAR(100),
City VARCHAR(100),
Population INT
)

INSERT tblPopulation VALUES					('COUNTRY1', 'STATE1','CITY1',9 ),
	('COUNTRY1', 'STATE1','CITY2',8 ), 		('COUNTRY1', 'STATE2','CITY1',5.5), 
	('COUNTRY1', 'STATE2','CITY2',7.5), 	('COUNTRY2', 'STATE1','CITY1',9.5), 
	('COUNTRY2', 'STATE1','CITY2',2.5),		('COUNTRY2', 'STATE2','CITY1',1.5),	
	('COUNTRY3', 'STATE1','CITY1',30),		('COUNTRY3', 'STATE1','CITY2',20)

-- GROUP BY	:	 USED TO REPORT UNIQUE VALUES OF A COLUMN & PERFORM AGGREGATIONS (SUM, MIN, MAX ..)
-- HAVING	:	 USED TO SPECIFY CONDITIONS ON THE GROUP BY COLUMNS.

-- QUERY 1: HOW TO REPORT LIST OF ALL POPULATION DETAILS?
SELECT * FROM tblPopulation

-- QUERY 2: HOW TO REPORT LIST OF ALL COUNTRY NAMES?
SELECT Country FROM tblPopulation

-- QUERY 3: HOW TO REPORT LIST OF ALL UNIQUE COUNTRIES DETAILS?
SELECT Country FROM tblPopulation 
GROUP BY Country

-- QUERY 4: HOW TO REPORT TOTAL POPULATION ?
SELECT sum(Population) AS TOTAL_POP FROM tblPopulation

-- QUERY 5: HOW TO REPORT COUNTRY WISE TOTAL POPULATION DETAILS?
SELECT		COUNTRY, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY	COUNTRY 

-- RULE: WHENEVER WE USE GROUP BY  : THE COLUMNS USED IN SELECT SHOULD BE USED IN GROUP BY.

-- QUERY 6: HOW TO REPORT COUNTRY WISE, STATE WISE  TOTAL POPULATION?
SELECT		COUNTRY, STATE, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY	COUNTRY, STATE
 

-- QUERY 7: HOW TO REPORT COUNTRY WISE, STATE WISE, CITY WISE TOTALS?
SELECT		COUNTRY, STATE, CITY, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY	COUNTRY, STATE, CITY


-- QUERY 8: HOW TO GIVE CONDITIONS ON GROUP BY (AGGREGATED) DATA ?
SELECT COUNTRY, STATE, CITY, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY COUNTRY , STATE, CITY
HAVING sum(Population) > 15


-- QUERY 9: HOW TO APPLY CONDITIONS BEFORE AND AFTER GROUP BY ?
SELECT COUNTRY, STATE, sum(Population) AS TOTAL_POP FROM tblPopulation
WHERE  COUNTRY = 'COUNTRY1'			-- TO SPECIFY CONDITIONS FOR NON AGGREGATE COLUMNS
GROUP BY COUNTRY, STATE 
HAVING sum(Population) > 5			-- TO SPECIFY CONDITIONS FOR AGGREGATE COLUMNS


-- QUERY 10: HOW TO REPORT TOTAL POPULATION USING ROLLUP  ?
SELECT  COUNTRY,  SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY COUNTRY

SELECT  COUNTRY,  SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)

SELECT  ISNULL(COUNTRY, 'GRAND TOTAL'), SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)

SELECT  ISNULL(COUNTRY, 'GRAND TOTAL') as COUNTRY, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)

SELECT  COALESCE(COUNTRY, 'GRAND TOTAL') as COUNTRY , SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(COUNTRY)


-- GROUPING : 0  = ORIGINAL ROW DATA.   1 = NEW ROW DATA
SELECT  ISNULL(COUNTRY, 'GRAND TOTAL') AS COUNTRY, SUM(Population) AS TOTAL_POPULATION,
GROUPING(COUNTRY)  FROM tblPopulation	
GROUP BY ROLLUP(COUNTRY)				


-- QUERY 11: HOW TO REPORT TOTAL POPULATION USING ROLLUP  ?
SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE)			-- COUNTRY WISE TOTALS + COUNTRY, STATE WISE TOTALS

SELECT  COALESCE(COUNTRY, 'GRAND TOTAL') as  COUNTRY, ISNULL(STATE, 'COUNTRY WISE TOTAL')  AS STATE, SUM(Population) AS TOTAL_POPULATION ,
GROUPING(COUNTRY),GROUPING(STATE) 
FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE)			-- COUNTRY WISE TOTALS + COUNTRY, STATE WISE TOTALS

-- QUERY 12: HOW TO REPORT TOTAL POPULATION USING CUBE  ?
SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY CUBE(COUNTRY, STATE)			-- COUNTRY WISE TOTALS + COUNTRY, STATE WISE TOTALS + STATE WISE TOTALS

-- QUERY 13: HOW TO REPORT SUB TOTALS, GRAND TOTALS WITH ROW STATUS ?
SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION, 
GROUPING(STATE) AS ROW_STATUS  FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE)  --  0 MEANS ORIGINAL DATA.   1 MEANS NEW ROW


-- QUERY 14: HOW TO REPORT ONLY SUB TOTALS AND GRAND TOTALS?
SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION, 
GROUPING(STATE) AS ROW_STATUS  FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE) 
HAVING GROUPING(STATE) = 1			-- aggregate function is grouping()

SELECT  COUNTRY,  SUM(Population) AS TOTAL_POPULATION, 
GROUPING(STATE) AS ROW_STATUS  FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE) 
HAVING GROUPING(STATE) = 1			-- aggregate function is grouping()


SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION, 
GROUPING(STATE) AS ROW_STATUS  FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE) 
HAVING GROUPING(STATE) = 0


-- QUERY 15: HOW TO REPORT ACTUAL DATA, SUB TOTALS, GRAND TOTALS IN ORDER?
SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION, 
GROUPING(STATE) AS ROW_STATUS  FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE) 
HAVING GROUPING(STATE) = 0
UNION ALL
SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION, 
GROUPING(STATE) AS ROW_STATUS  FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE) 
HAVING GROUPING(STATE) = 1


create view vw_querystore
as
SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION, 
GROUPING(STATE) AS ROW_STATUS  FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE) 
HAVING GROUPING(STATE) = 0
UNION ALL
SELECT  COUNTRY, STATE, SUM(Population) AS TOTAL_POPULATION, 
GROUPING(STATE) AS ROW_STATUS  FROM tblPopulation
GROUP BY ROLLUP(COUNTRY, STATE) 
HAVING GROUPING(STATE) = 1

select * from vw_querystore

