-- CONFIGURE LOG SHIPPING

-- PERFORM CHANGES @ PRIMARY:
SELECT * INTO LS_TEST FROM SYSMESSAGES 

-- MONTOR BACKUP, COPY, RESTORE JOBS

-- STOP PRIMARY SERVER
-- HOW TO PERFORM MANUAL FAILOVER?
	-- DISABLE COPY & RESTORE JOBS
	-- IDENTIFY PENDING LOG BACKUPS: COPY, RESTORE

RESTORE LOG [UNIVERSITYDATABASE] FROM DISK = '\\Sqlschool\SHARE2\UNIVERSITYDATABASE_20200630062000.trn' WITH NORECOVERY


RESTORE LOG [UNIVERSITYDATABASE] FROM DISK = '\\Sqlschool\SHARE2\UNIVERSITYDATABASE_20200630062001.trn' WITH NORECOVERY


RESTORE LOG [UNIVERSITYDATABASE] FROM DISK = '\\Sqlschool\SHARE2\UNIVERSITYDATABASE_20200630062002.trn' WITH RECOVERY


-- IF 1ST SERVER IS ONLINE BACK, LOG SHIPPING FAILS. REASON :  2ND SERVER IS ONLINE. 
-- TO CONTINUE LOG SHIPPING, WE NEED TO CONVERT 2ND DATABASE FROM ONLINE TO RESTORING.
BACKUP LOG [UNIVERSITYDATABASE] TO DISK = '\\SQLSCHOOL\SHARE2\TAL_LOG.trn' WITH NORECOVERY


-- HOW TO MODIFY THE MODE OF LOG SHIPPING. FROM NORECOVERY TO STANDBY MODE?
-- FROM 1ST SERVER:  CHANGE LOG SHIPPING MODE TO READ ONLY. DELAY RESTORING ATLEAST FEW MINUTES. 