-- FROM AZURE SQL SERVER: MASTER DATABASE
SELECT  
db.name [Database],        ds.edition [Edition],        ds.service_objective [Service Objective]
FROM    sys.database_service_objectives   AS ds
JOIN    sys.databases                     AS db ON ds.database_id = db.database_id;


-- FROM AZURE SQL SERVER: STRETCH DATABASE
--EXPAND DATABASE > TABLES > TEST QUERY THE STRETCH TABLE



-- FROM ON-PREMISE SOURCE:
SELECT * FROM SALES_DATA

SELECT * FROM SALES_DATA WHERE SalesAmount <= 50		-- QUERIED FROM STRETCH DATABASE
SELECT * FROM SALES_DATA WHERE SalesAmount > 50			-- QUERIED FROM ON-PREMISE SOURCE 


-- VERIFY THE SIZE OF THE TABLE
EXEC SP_SPACEUSED 'SALES_DATA'		-- 1368 KB
DBCC CHECKTABLE ('SALES_DATA')		-- 1696 rows in 125 pages


-- RIGHT CLICK THE SOURCE TABLE > STRETCH > PAUSE
											DISABLE
												LEAVE THE DATA IN AZURE
												BRING BACK THE DATA FROM AZURE		**

-- VERIFY THE SIZE OF THE TABLE
EXEC SP_SPACEUSED 'SALES_DATA'		-- 1392 KB
DBCC CHECKTABLE ('SALES_DATA')		-- 6434 rows in 128 pages 


-- RIGHT CLICK DATABASE > STRETCH  > DISABLE

	