CREATE DATABASE [SQLDBA];

SELECT * FROM sys.databases	;

USE [SQLDBA];

-- TABLE 1:  CUSTOMERS_DATA TABLE
CREATE TABLE [CUSTOMER_DATA]
(
[CustomerKey]	INT PRIMARY KEY,
[FirstName]		VARCHAR(30) NOT NULL,
[MiddleName]	VARCHAR(30) NOT NULL,
[LastName]		VARCHAR(30) NOT NULL,	
[Gender]		CHAR(1) NOT NULL CHECK ([Gender] IN ('M','F')),
[MaritalStatus]	CHAR(1) NOT NULL CHECK ([MaritalStatus] IN ('M','S')),
[Income]		FLOAT NOT NULL CHECK ([Income] >= 10000)
);

DROP TABLE [CUSTOMER_DATA];

-- TABLE 2:	 PRODUCTS_DATA TABLE
CREATE TABLE [PRODUCTS_DATA]
(
[ProductKey]	INT PRIMARY KEY,
[ProductName]	VARCHAR(30) NOT NULL,
[Class]			CHAR(1) NOT NULL CHECK ([Class] IN ('L','M','H')),
[Color]			VARCHAR(20) NOT NULL CHECK ([Color] IN ('White','Black', 'Red', 'Green','Other')),
[UnitPrice]		FLOAT NOT NULL CHECK ([UnitPrice] >= 1)
);

-- TABLE 3:  TIME_DATA TABLE
CREATE TABLE [TIME_DATA]
(
[TimeKey]	INT PRIMARY KEY,
[YEAR]		INT,
[QUARTER]	INT,
[MONTH]		VARCHAR(30),
[WEEK]		INT,
[DAY]		DATE DEFAULT GETDATE()
);

SELECT GETDATE();
SELECT GETUTCDATE();

-- TABLE 4:	 SALES_DATA
CREATE TABLE [SALES_DATA]
(
[SALE_ID]			INT		IDENTITY(10001,1),
[CustomerKey]		INT		REFERENCES [CUSTOMER_DATA](CustomerKey),
[ProductKey]		INT		REFERENCES [PRODUCTS_DATA](ProductKey),
[TimeKey]			INT		REFERENCES [TIME_DATA](TimeKey),
[SalesAmount]		FLOAT	CHECK ([SalesAmount] >= 1) NOT NULL,
[TaxAmt]			FLOAT	CHECK ([TaxAmt] >= 0.5) NOT NULL
);


-- NOW, LETS INSERT SOME TEST DATA
INSERT INTO [CUSTOMER_DATA] VALUES (1001, 'JOHN', 'M','GEORGE', 'M','M', 250000)
INSERT INTO [CUSTOMER_DATA] VALUES (1002, 'AMIN', 'A','SHAIK', 'M','S', 150000)
INSERT INTO [CUSTOMER_DATA] VALUES (1003, 'SAI', ' ','JACK', 'M','S', 200000)

INSERT INTO PRODUCTS_DATA VALUES (101, 'CAPS', 'M', 'RED', 2),(102, 'CAPS', 'H', 'RED', 2)
INSERT INTO PRODUCTS_DATA VALUES (103, 'GLOVES', 'M', 'GREEN', 2),(104, 'GLOVES', 'H', 'GREEN', 2)

INSERT INTO TIME_DATA VALUES (1, 2020, 1, 'JANUARY', 4, '2020-01-30'), (2, 2020, 1, 'JANUARY', 4,'2020-01-31')

INSERT INTO SALES_DATA VALUES (1001, 101, 1, 6300, 130)
INSERT INTO SALES_DATA VALUES (1002, 104, 2, 9500, 180)
INSERT INTO SALES_DATA VALUES (1003, 101, 1, 2300, 330)
INSERT INTO SALES_DATA VALUES (1001, 104, 2, 1900, 180)
INSERT INTO SALES_DATA VALUES (1002, 102, 1, 3020, 130)
INSERT INTO SALES_DATA VALUES (1003, 104, 2, 9200, 380)
INSERT INTO SALES_DATA VALUES (1001, 102, 1, 3100, 304)
INSERT INTO SALES_DATA VALUES (1002, 104, 2, 1900, 840)
INSERT INTO SALES_DATA VALUES (1003, 102, 1, 5300, 320)
INSERT INTO SALES_DATA VALUES (1003, 104, 2, 9600, 280)
INSERT INTO SALES_DATA VALUES (1002, 102, 1, 3070, 230)
INSERT INTO SALES_DATA VALUES (1003, 104, 2, 5900, 480)




-- QUERY 1:	HOW TO REPORT LIST OF ALL SALES?
SELECT * FROM SALES_DATA


-- QUERY 2:	HOW TO REPORT LIST OF ALL PRODUCTS?
SELECT * FROM PRODUCTS_DATA


-- QUERY 3: HOW TO REPORT PRODUCT WISE SALES?
SELECT * FROM PRODUCTS_DATA
INNER JOIN 
SALES_DATA
ON
PRODUCTS_DATA.ProductKey = SALES_DATA.ProductKey










