
USE [DB_OBJECTS]
GO

SELECT * FROM CUSTOMERS_DATA 
SELECT * FROM PRODUCTS_DATA 
SELECT * FROM TIME_DATA 
SELECT * FROM SALES_DATA 


-- QUERY  #1: HOW TO REPORT TIME DATA AND SALES DATA - SIDE BY SIDE ?
SELECT *
FROM TIME_DATA 
INNER JOIN
SALES_DATA
ON
SALES_DATA.OrderDateKey = TIME_DATA.TimeKey


-- QUERY  #2: HOW TO REPORT YEAR DATA FROM TIME TABLE AND RESPECTIVE (MATCHING) SALES DATA FROM SALES TABLE?
SELECT CalendarYear, SalesAmount
FROM TIME_DATA 
INNER JOIN
SALES_DATA
ON
SALES_DATA.OrderDateKey = TIME_DATA.TimeKey



-- QUERY  #3: HOW TO REPORT YEAR WISE TOTAL SALES?
SELECT CalendarYear, SUM(SalesAmount) AS TOTAL_SALES
FROM TIME_DATA 
INNER JOIN
SALES_DATA
ON
SALES_DATA.OrderDateKey = TIME_DATA.TimeKey
GROUP BY CalendarYear			-- GROUP BY IS USED TO REPORT UNIQUE VALUES AND AGGREGATES.



-- QUERY 4: HOW TO REPORT YEAR WISE, QUARTER WISE TOTAL SALES?
SELECT		CalendarYear,  CalendarQuarter, SUM(SalesAmount) AS TOTAL_SALES
FROM TIME_DATA 
INNER JOIN
SALES_DATA
ON
SALES_DATA.OrderDateKey = TIME_DATA.TimeKey
GROUP BY	CalendarYear,  CalendarQuarter


-- QUERY 5: HOW TO REPORT YEAR WISE, QUARTER WISE, MONTH WISE TOTAL SALES?
SELECT CalendarYear,  CalendarQuarter, ENGLISHMONTHNAME, SUM(SalesAmount) AS TOTAL_SALES
FROM TIME_DATA 
INNER JOIN
SALES_DATA
ON
SALES_DATA.OrderDateKey = TIME_DATA.TimeKey
GROUP BY CalendarYear,  CalendarQuarter, ENGLISHMONTHNAME


-- EXAMPLES TO JOIN THREE TABLES:
SYNTAX	:		(A JOIN B) JOIN C


-- QUERY 6:	HOW TO REPORT YEAR WISE TOTAL SALES FOR EACH PRODUCT ?
SELECT *
FROM TIME_DATA 
INNER JOIN
SALES_DATA
ON SALES_DATA.OrderDateKey = TIME_DATA.TimeKey
INNER JOIN
PRODUCTS_DATA 
ON SALES_DATA.PRODUCTKEY = PRODUCTS_DATA.PRODUCTKEY


-- QUERY 7:	HOW TO REPORT YEAR WISE TOTAL SALES FOR EACH PRODUCT ?
SELECT CalendarYear, EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES
FROM TIME_DATA 
INNER JOIN
SALES_DATA
ON
SALES_DATA.OrderDateKey = TIME_DATA.TimeKey
INNER JOIN
PRODUCTS_DATA 
ON
SALES_DATA.PRODUCTKEY = PRODUCTS_DATA.PRODUCTKEY
GROUP BY CalendarYear, EnglishProductName


-- EXAMPLES TO JOIN FOUR TABLES:
SYNTAX	:		( (A JOIN B) JOIN C ) JOIN D

-- QUERY 8:	HOW TO REPORT YEAR WISE TOTAL SALES FOR EACH PRODUCT AND EACH CUSTOMER?
SELECT TIME_DATA.CalendarYear, PRODUCTS_DATA.EnglishProductName, CUSTOMERS_DATA.FirstName,  
SUM(SALES_DATA.SalesAmount) AS TOTAL_SALES
FROM TIME_DATA 
INNER JOIN
SALES_DATA
ON SALES_DATA.OrderDateKey = TIME_DATA.TimeKey
INNER JOIN
PRODUCTS_DATA 
ON SALES_DATA.PRODUCTKEY = PRODUCTS_DATA.PRODUCTKEY
INNER JOIN
CUSTOMERS_DATA 
ON SALES_DATA.CUSTOMERKEY = CUSTOMERS_DATA.CUSTOMERKEY
GROUP BY TIME_DATA.CalendarYear, PRODUCTS_DATA.EnglishProductName, CUSTOMERS_DATA.FirstName



-- QUERY 9:	
SELECT T.CalendarYear, P.EnglishProductName, C.FirstName,  SUM(S.SalesAmount) AS TOTAL_SALES
FROM TIME_DATA  as T
INNER JOIN
SALES_DATA as S
ON
S.OrderDateKey = T.TimeKey
INNER JOIN
PRODUCTS_DATA as P
ON
S.PRODUCTKEY = P.PRODUCTKEY
INNER JOIN
CUSTOMERS_DATA as C
ON
S.CUSTOMERKEY = C.CUSTOMERKEY
GROUP BY T.CalendarYear, P.EnglishProductName, C.FirstName




-- QUERY 10 :	
SELECT T.CalendarYear, P.EnglishProductName, C.FirstName + C.LastName ,  SUM(S.SalesAmount) AS TOTAL_SALES
FROM TIME_DATA  as T
INNER JOIN
SALES_DATA as S
ON
S.OrderDateKey = T.TimeKey
INNER JOIN
PRODUCTS_DATA as P
ON
S.PRODUCTKEY = P.PRODUCTKEY
INNER JOIN
CUSTOMERS_DATA as C
ON
S.CUSTOMERKEY = C.CUSTOMERKEY
GROUP BY T.CalendarYear, P.EnglishProductName, C.FirstName + C.LastName




-- QUERY 11 :	
SELECT T.CalendarYear, P.EnglishProductName, C.FirstName +  ' ' + C.LastName AS [FULL NAME],  
SUM(S.SalesAmount) AS TOTAL_SALES
FROM TIME_DATA  as T
INNER JOIN
SALES_DATA as S
ON
S.OrderDateKey = T.TimeKey
INNER JOIN
PRODUCTS_DATA as P
ON
S.PRODUCTKEY = P.PRODUCTKEY
INNER JOIN
CUSTOMERS_DATA as C
ON
S.CUSTOMERKEY = C.CUSTOMERKEY
GROUP BY T.CalendarYear, P.EnglishProductName, C.FirstName +  ' ' + C.LastName 


-- QUERY 12: HOW TO REPORT YEAR WISE SALES FOR ALL PRODUCTS WITH MAXIMUM PRICE?
SELECT 
T.CalendarYear, P.EnglishProductName,  SUM(S.SalesAmount) AS TOTAL_SALES
FROM TIME_DATA  as T
INNER JOIN
SALES_DATA as S
ON
S.OrderDateKey = T.TimeKey
INNER JOIN
PRODUCTS_DATA as P
ON
S.PRODUCTKEY = P.PRODUCTKEY
INNER JOIN
CUSTOMERS_DATA as C
ON
S.CUSTOMERKEY = C.CUSTOMERKEY
WHERE	P.LISTPRICE IN (SELECT MAX(LISTPRICE) FROM PRODUCTS_DATA)
GROUP BY T.CalendarYear, P.EnglishProductName





	----------------------------------- CASE STUDY FOR QUERY WRITING -------------------------
-- Q1:	HOW TO REPORT YEAR WISE TOTAL SALES?
-- Q2:  HOW TO REPORT YEAR WISE, QUARTER WISE TOTAL SALES AND TOTAL TAX?
-- Q3:  HOW TO REPORT YEAR WISE, QUARTER WISE, MONTH WISE TOTAL SALES AND TOTAL TAX?
-- Q4:  HOW TO REPORT YEAR WISE, QUARTER WISE TOTAL SALES AND TOTAL TAX FOR JUNE MONTH ?
-- Q5:  HOW TO REPORT CLASS WISE, COLOR WISE PRODUCTS FOR EACH YEAR BASED ON ASC ORDER OF SALES?
-- Q6:	HOW TO REPORT AVERAGED SALES AND AVERAGED TAX FOR SUCH PRODUCTS WITH MAXIMUM LIST PRICE AND HIGHEST STANDARD PRICE?
-- Q7:	HOW TO REPORT AVERAGED SALES AND AVERAGED TAX FOR SUCH HIGH CLASS RED COLORED PRODUCTS WITH MAXIMUM LIST PRICE FROM?
-- Q8:	HOW TO COMBINE THE RESULTS FROM ABOVE TWO QUERIES.
-- Q9:	HOW TO REPORT AVERAGE SALES AND AVERAGE TAX FOR ALL FEMALE CUSTOMERS FROM 2001 TO 2003 YEAR?
-- Q10: HOW TO REPORT YEAR WISE, CUSTOMER WISE, PRODUCT WISE TOTAL SALES AND TOTAL TAX ABOVE 1000 USD?
	

-- WE HAVE USER INTERFACE IN MSBI AND POWER BI TO AUTO GENERATE THE SQL QUERIES. 





